name: Keep Workspace Alive with SSH

on:
  workflow_dispatch:
  # schedule:
  # - cron: '*/9 * * * *'
  # - cron: '*/9 4-16 * * *' # 12:00-00:00 每9分钟运行一次

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    environment: SecretId
    permissions:
      contents: read
      actions: write
    env:
      ALIST_SPACE_KEY: ${{ secrets.ALIST_SPACE_KEY }}
      SECRET_ID: ${{ secrets.SECRET_ID }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      SSH_URL: ${{ secrets.SSH_URL }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: keep-alive
        id: ssh-keep-alive
        run: npx tsx src/keep-alive.ts
